### PR TITLE
UI improvement

### PR DESCRIPTION
**Pull request by Nhlanhla-advocate**

### CODE REVIEW

**Comment by mpilomthiyane97** [comment]
Your branch has conflicts,  fix them before merging

**Review by mpilomthiyane97 — CHANGES_REQUESTED** [review]
Your branch has conflicts, please fix them before merging

**Comment by Nhlanhla-advocate** [comment]
I have fixed the conflicts, please review my code.

**Review by ImisebenziEmihle — APPROVED** [review]
Looks okay so far. thanks @Nhlanhla-advocate

**Pull request merged**
