### PR TITLE
Updated user mode

### PR DESCRIPTION
**Pull request by ImisebenziEmihle**
I added the tokenblacklist and role field on the new user schema, I also changed the field, name to username.

### CODE REVIEW

**Comment by NokulungaM** [comment]
Approved, wait for second reviewer to merge to main.

**Comment by NokulungaM** [comment]
Approved, wait for second reviewer to merge to main.

**Review by mpilomthiyane97 — APPROVED** [review]

**Review by NokulungaM — CHANGES_REQUESTED** [review]
Not approved. Please resolve conflicts.

**Comment by ImisebenziEmihle** [comment]
@NokulungaM @mpilomthiyane97 , I have conflicts on this branch on the conflicting files as stated. I cannot the any conflicting lines of code in the code when I compare it to the main. So Im trying to understand where the conflicts are, please assist. Note, I only changed name to username, added the role and tokenblacklist field only on this file.

**Pull request closed without merging**
